blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from .apps import BlogConfig
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogListViewAll,
)

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('listAll/', BlogListViewAll.as_view(), name='blog_list_all'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('<int:pk>/update/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:  # dz_20.1
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # dz_20.1

blog/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(unique=True, max_length=200, verbose_name="Ссылка")
    content = models.TextField(verbose_name="Содержимое")
    preview_image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name="Превью")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    view_count = models.PositiveIntegerField(default=0, verbose_name="Просмотры")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        permissions = [
            ("can_title", "Можно менять заголовок"),
            ("can_content", "Можно менять описание"),
            ("can_preview_image", "Можно менять изображение к блогу"),
            ("can_is_published", "Можно отменять публикацию"),

        ]

blog/forms.py
# Домашнее задание 22.1 - Формы в Django
from django import forms
from django.forms import ModelForm

from blog.models import Blog


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        exclude = ['slug', 'view_count', 'created_at', 'updated_at']  # 22.1 - исключаем поля, которые не нужны в форме


class BlogContentManagerForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'preview_image', 'is_published']

blog/views.py
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm, BlogContentManagerForm
from blog.models import Blog


class BlogListViewAll(ListView):
    model = Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save()
        return obj


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm  # 22.1 - Формы в Django вместо fields
    success_url = reverse_lazy('blog:blog_list')

    class BlogListView(ListView):
        model = Blog  # Подставьте вашу модель
        template_name = 'blog/blog_list.html'  # Подставьте ваш шаблон

    def form_valid(self, form):
        if form.is_valid():
            new_slug = form.save()
            new_slug.slug = slugify(new_slug.title)
            new_slug.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm  # 22.1 - формы в Django вместо fields
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_slug = form.save()
            new_slug.slug = slugify(new_slug.title)
            new_slug.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user.has_perms([
            "blog.can_title",
            "blog.can_content",
            "blog.can_preview_image",
            "blog.can_is_published",
        ]):
            return BlogContentManagerForm
        else:
            return BlogForm
        # raise PermissionDenied


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends "catalog/home.html" %}

{% block content %}
    <div class="container mt-5">
        <h1>Вы уверены, что хотите удалить "{{ blog.title }}"?</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" href="{% url 'blog:blog_list' %}" class="btn btn-danger">Да, удалить</button>
        </form>
        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary mt-3">Нет, отменить</a>
    </div>
    </body>
{% endblock %}



    

blog/templates/blog/blog_detail.html
{% extends "catalog/home.html" %}

{% block content %}
<body>
    <div class="container mt-5">
        <h1>{{ blog.title }}</h1>
        {% if blog.preview_image %}
            <img src="{{ blog.preview_image.url }}" alt="Preview" class="img-fluid">
        {% else %}
            <p>Нет изображения</p>
        {% endif %}
        <p>{{ blog.content }}</p>
        <p>slug : {{ blog.slug }}</p>
        <p>Создан в: {{ blog.created_at }}</p>
        <p>Опубликовано: {% if blog.is_published %}Да{% else %}Нет{% endif %} </p>
        <p>Просмотров: {{ blog.view_count }}</p>
        {% if perms.blog.can_title and perms.blog.can_content and perms.blog.can_preview_image and perms.blog.can_is_published %}
        <a href="{% url 'blog:blog_update' blog.pk %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'blog:blog_delete' blog.pk %}" class="btn btn-danger">Удалить</a>
        {% endif %}
        <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">Обратно к списку</a>
    </div>
</body>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "catalog/home.html" %}

{% block content %}
<body>
<div class="container mt-5">
    <h1>Создать/редактировать сообщение в блоге</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">
            {% if object.pk %}
            Изменить
            {% else %}
            Создать
            {% endif %}
        </button>
        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
</body>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "catalog/home.html" %}

{% block content %}
    <div class="container mt-5 d-flex flex-column align-items-center">
        <h1 class="text-center">Опубликованные посты</h1>
        {% if perms.blog.can_title and perms.blog.can_content and perms.blog.can_preview_image and perms.blog.can_is_published %}
            <div class="d-flex justify-content-center mb-3">
                <a href="{% url 'blog:blog_create' %}" class="btn btn-success mr-2">Создать новый пост</a>
                <a href="{% url 'blog:blog_list_all' %}" class="btn btn-secondary">Показать так же не опубликованные
                    посты</a>
            </div>
        {% endif %}
        <ul class="list-group w-50">
            {% for blog in object_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_detail' blog.pk %}" class="font-weight-bold">{{ blog.title }}</a>
                    <div class="border p-3 mt-2">
                        {{ blog.content }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}