blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from .apps import BlogConfig
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogListViewAll,
)

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('listAll/', BlogListViewAll.as_view(), name='blog_list_all'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('<int:pk>/update/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import HomeListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    CategoryListView, CategoryDetailView
from .views import ContactsView

app_name = CatalogConfig.name


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('catalog/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('catalog/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('catalog/<int:pk>/edit/', never_cache(ProductUpdateView.as_view()), name='product_edit'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:  # dz_20.1
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # dz_20.1

catalog/models.py
from django.db import models

from users.models import Users

# dz_20.1 все модели созданы в дз 20.1 до 34 строки

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='Наименование категории',
                            help_text='Введите наименование категории')
    description = models.TextField(verbose_name='Описание категории', **NULLABLE)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = None
    name = models.CharField(max_length=225, verbose_name='Наименование продукта')
    description = models.TextField(verbose_name='Описание продукта', **NULLABLE)
    picture = models.ImageField(upload_to='product/photo', verbose_name='Изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория',
                                 **NULLABLE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(Users, verbose_name='Собственник товара', **NULLABLE, on_delete=models.SET_NULL)

    is_published = models.BooleanField(default=False, verbose_name="Опубликован")

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name', 'category', 'price']
        permissions = [
            ("can_is_published_product", "Можно отменить публикацию продукта"),
            ("can_description_product", "Можно менять описание любого продукта"),
            ("can_category_product", "Можно изменить категорию продукта"),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(Product, related_name='versions', on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=50)
    version_name = models.CharField(max_length=255)
    is_current = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ['product']

    def __str__(self):
        return f" {self.version_name} ({self.version_number})"

catalog/forms.py
from django import forms
from .models import Product, Version

PROHIBITED_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['slug', 'view_count', 'created_at', 'updated_at', 'owner']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        for word in PROHIBITED_WORDS:
            if word in name.lower():
                raise forms.ValidationError(f"Название продукта не должно содержать запрещенное слово: {word}")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        for word in PROHIBITED_WORDS:
            if word in description.lower():
                raise forms.ValidationError(f"Описание продукта не должно содержать запрещенное слово: {word}")
        return description


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['is_published', 'category', 'description']


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['product', 'version_number', 'version_name', 'is_current']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.forms import inlineformset_factory, forms, BaseInlineFormSet

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_from_cach


class HomeListView(ListView):
    model = Product
    template_name = 'home.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context['object_list']

        active_versions = {}
        for product in products:
            current_versions = product.versions.filter(is_current=True)
            active_versions[product.id] = current_versions.first()

        context['active_versions'] = active_versions
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'catalog/product_form.html'

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'catalog/product_form.html'

    from django.contrib.auth.models import Group
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            # Проверяем, входит ли пользователь в группу Moderators
            moderators_group = Group.objects.get(name='Moderators')
            # Если пользователь не в группе Moderators, не включаем форму для версий
            if not moderators_group in self.request.user.groups.all():
                context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data.get('formset')
        if formset.is_valid():
            active_versions_count = sum(1 for form in formset if form.cleaned_data.get('is_current'))
            if active_versions_count > 1:
                form.add_error(None, 'Вы можете выбрать только одну активную версию для продукта.')  # Добавляем ошибку
                return self.form_invalid(form)
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perms([
            "catalog.can_is_published_product",
            "catalog.can_description_product",
            "catalog.can_category_product",
        ]):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    template_name = 'catalog/product_confirm_delete.html'


class ContactsView(View):
    template_name = 'catalog/contacts.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"Имя-{name}, Телефон-{phone}, Сообщение-{message}")
        return render(request, self.template_name)


class CategoryListView(ListView):
    template_name = 'catalog/category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return get_category_from_cach()


class CategoryDetailView(ListView):
    template_name = 'catalog/category_detail.html'
    context_object_name = 'products'

    def get_queryset(self):
        category_id = self.kwargs.get('pk')
        return Product.objects.filter(category__id=category_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(pk=self.kwargs.get('pk'))
        return context

catalog/templates/catalog/category_detail.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <h1>Товары в категории: {{ category.name }}</h1>

    <ul>
        {% for product in products %}
            <li>{{ product.name }} - {{ product.price }} руб.</li>
        {% empty %}
            <li>Товары не найдены.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'catalog:category_list' %}">Назад к списку категорий</a>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <h1>Список категорий</h1>
    
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'catalog:category_detail' category.pk %}">{{ category.name }}</a></li>
        {% empty %}
            <li>Категории не найдены.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block extra_styles %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
    }
    .container {
        background-color: #ffffff;
        padding: 20px 40px;
        border-radius: 10px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        text-align: center;
        max-width: 600px;
        margin: 40px auto;
    }
    h1 {
        color: #333333;
        margin-bottom: 20px;
    }
    ul {
        list-style-type: none;
        padding: 0;
    }
    li {
        background-color: #e7e7e7;
        margin: 5px 0;
        padding: 10px;
        border-radius: 5px;
        color: #333333;
    }
    li:hover {
        background-color: #d4d4d4;
    }
    a {
        color: #333333;
        text-decoration: none;
    }
    a:hover {
        text-decoration: underline;
    }
</style>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <from method="pos>">
        {% csrf_token %}
        <inpyt type="text" name="name"/>
        <br>
        <inpyt type="text" name="phone"/>
        <br>
        <texstarea name="massage"></texstarea>
        <br>
        <inpyt type="submit" value="Отправить"/>
        <br>
    </from>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% include 'includs/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>RUS</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>5410781149</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Новосибриск, ул. Восход, 58</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Чем могу Вам помочь" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% include 'includs/inc_menu.html' %}


{% block content %}

{% endblock %}


<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            RViktorV
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
  <h2>Удалить продукт</h2>
  <form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
    <button type="submit">Удалить</button>
  </form>
  <a href="{% url 'catalog:home' %}">Назад к списку продуктов</a>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

    <div class="container">

        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row row row row-cols-2 row-cols-sm-2 row-cols-md-2 g-3">
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ product.picture | media_filter }}">
                            <div class="card-body">
                                <p class="card-text">{{ product.name }} - Категория товара: {{ product.category }}</p>
                                <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                                <p class="card-text">Цена: {{ product.price }} руб.</p>
                                {% if active_version %}
                                    <p class="card-text">Текущая версия: {{ active_version.version_name }}
                                        ({{ active_version.version_number }})</p>
                                {% endif %}
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-primary" href="{% url 'catalog:home' %}" role="button">К
                                            каталогу</a>
                                        {% if perms.catalog.can_is_published_product and perms.catalog.can_description_product and perms.catalog.can_category_product %}
                                            <a class="btn btn-warning"
                                               href="{% url 'catalog:product_edit' product.pk %}" role="button">Редактировать</a>
                                        {% endif %}
                                        {% if user == product.owner %}
                                            <a class="btn btn-danger"
                                               href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить
                                                продукт</a>
                                            <a class="btn btn-warning"
                                               href="{% url 'catalog:product_edit' product.pk %}" role="button">Редактировать</a>
                                            </div>
                                        {% endif %}
                                    <small class="text-body-secondary">9 мин</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}

{% block content %}
    <div class="container mt-4">
        <h2>{% if object %}Редактировать продукт{% else %}Создать продукт{% endif %}</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <!-- Левая колонка: форма редактирования продукта -->
                <div class="col-md-6">
                    {{ form.as_p }}
                </div>

                <!-- Правая колонка: форма редактирования версий продукта -->
                <div class="col-md-6">
                    <h3>Добавить/Редактировать версию</h3>

                    {% if formset.non_form_errors %}
                        <div class="alert alert-danger">
                            {{ formset.non_form_errors }}
                        </div>
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Версия продукта
                            </h3>
                        </div>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                {{ form.as_p }}
                            {% endfor %}
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>

            <div class="mt-4">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn btn-secondary" href="{% url 'catalog:home' %}">Назад к списку продуктов</a>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% load custom_tags %}
{% block content %}

<div class="container">

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h1 class="display-4">Каталог</h1>

            </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for item in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ item.picture | media_filter }}">
                        <div class="card-body">
                            <p class="card-text">{{ item.name }} - Категория товара: {{ item.category }}</p>
                            <p class="card-text">Описание: {{ item.description|truncatechars:100 }}</p>
                            <p class="card-text">Цена: {{ item.price }}</p>
                            {% with active_version=active_versions|get_item:item.id %}
                            {% if active_version %}
                            <p class="card-text">Текущая версия: {{ active_version.version_name }}, Номер верси: {{ active_version.version_number }}</p>
                            {% endif %}
                            {% endwith %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'catalog:product_detail' item.pk %}"
                                       role="button">Смотреть</a>
                                </div>
                                <small class="text-body-secondary">9 мин</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}